resolver: ghc-7.10.2
packages:
- '.'
- .stack-work/downloaded/9d4d7f7ffc164258e2ac2e578ba3d3c57f5f5134cbc77253efa07d7d6d60e059.git/

extra-deps:
- GLURaw-1.5.0.2
- GLUT-2.7.0.3
- JuicyPixels-3.2.6.2
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.5.0
- StateVar-1.1.0.1
- bmp-1.2.5.2
- convertible-1.1.1.0
- freenect-1.2.1
- friday-0.2.2.0
- friday-juicypixels-0.1.0.2
- gloss-1.9.4.1
- gloss-juicy-0.2
- gloss-rendering-1.9.3.1
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- primitive-0.6.1.0
- ratio-int-0.1.2
- stm-2.4.4
- text-1.2.1.3
- vector-0.11.0.0
- zlib-0.6.1.1

flags:
  text:
    integer-simple: false
